
development:  
  adapter: postgresql
  encoding: unicode
  database: backend_dev
  pool: 5
  username: matiasdim
  password:

test:  
  adapter: postgresql
  encoding: unicode
  database: backend_test
  pool: 5
  username: matiasdim
  password:

production:
  adapter: postgresql
  encoding: utf8
  pool: 15