# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2da6217f621b37cc54923ed115b94c2fd0c0d9e49435da20e571c7e17f8cac1144aee2249aab37a242b16578d11abbdc1c2a8c75290703831b4497c6cd9e825

test:
  secret_key_base: 922405729b141abc9fb4c700c3d5d16d38ffad21edbd2ad4c5856456a14e7c64e7657ca584eab3adb80d70efc8e9d79296f9e5fcf2fe8a6581e988f01600cd42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
